CatenaMediaBundle\Entity\SportClass:
    type: entity
    table: sport_class
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        provider:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        maxrepdate:
            type: date
            nullable: true
            column: maxRepDate
        maxreptime:
            type: time
            nullable: true
            column: maxRepTime
    lifecycleCallbacks: {  }
